# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

GCC_BIN = 
PROJECT = Micromouse_Firmware
OBJECTS = 	.\main.o	\
			.\motors.o	\
			.\PID.o		\
			.\encoders.o	\
			.\debug.o	\
			.\Kalman.o
			

SYS_OBJECTS_MBED_COMMON = 	\
				.\libraries\mbed\common\assert.o   \
				.\libraries\mbed\common\board.o   \
				.\libraries\mbed\common\error.o   \
				.\libraries\mbed\common\gpio.o   \
				.\libraries\mbed\common\mbed_interface.o   \
				.\libraries\mbed\common\pinmap_common.o   \
				.\libraries\mbed\common\rtc_time.o   \
				.\libraries\mbed\common\semihost_api.o   \
				.\libraries\mbed\common\us_ticker_api.o   \
				.\libraries\mbed\common\wait_api.o   \
				.\libraries\mbed\common\BusIn.o   \
				.\libraries\mbed\common\BusInOut.o   \
				.\libraries\mbed\common\BusOut.o   \
				.\libraries\mbed\common\CallChain.o   \
				.\libraries\mbed\common\CAN.o   \
				.\libraries\mbed\common\Ethernet.o   \
				.\libraries\mbed\common\FileBase.o   \
				.\libraries\mbed\common\FileLike.o   \
				.\libraries\mbed\common\FilePath.o   \
				.\libraries\mbed\common\FileSystemLike.o   \
				.\libraries\mbed\common\FunctionPointer.o   \
				.\libraries\mbed\common\I2C.o   \
				.\libraries\mbed\common\I2CSlave.o   \
				.\libraries\mbed\common\InterruptIn.o   \
				.\libraries\mbed\common\InterruptManager.o   \
				.\libraries\mbed\common\LocalFileSystem.o   \
				.\libraries\mbed\common\RawSerial.o   \
				.\libraries\mbed\common\retarget.o   \
				.\libraries\mbed\common\Serial.o   \
				.\libraries\mbed\common\SerialBase.o   \
				.\libraries\mbed\common\SPI.o   \
				.\libraries\mbed\common\SPISlave.o   \
				.\libraries\mbed\common\Stream.o   \
				.\libraries\mbed\common\Ticker.o   \
				.\libraries\mbed\common\Timeout.o   \
				.\libraries\mbed\common\Timer.o   \
				.\libraries\mbed\common\TimerEvent.o

SYS_OBJECTS_MBED_TARGETS = 	\
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_adc.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_adc_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_can.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_cortex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_crc.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_cryp.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_cryp_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_dac.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_dac_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_dcmi.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_dma.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_dma2d.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_dma_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_eth.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_flash.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_flash_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_flash_ramfunc.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_gpio.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_hash.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_hash_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_hcd.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_i2c.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_i2c_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_i2s.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_i2s_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_irda.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_iwdg.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_ltdc.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_nand.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_nor.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_pccard.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_pcd.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_pcd_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_pwr.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_pwr_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_rcc.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_rcc_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_rng.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_rtc.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_rtc_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_sai.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_sd.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_sdram.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_smartcard.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_spi.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_sram.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_tim.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_tim_ex.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_uart.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_usart.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_hal_wwdg.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_ll_fmc.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_ll_fsmc.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_ll_sdmmc.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\stm32f4xx_ll_usb.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\TARGET_MTS_MDOT_F405RG\cmsis_nvic.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\TARGET_MTS_MDOT_F405RG\hal_tick.o   \
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\TARGET_MTS_MDOT_F405RG\system_stm32f4xx.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\analogin_api.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\analogout_api.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\gpio_api.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\gpio_irq_api.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\i2c_api.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\mbed_overrides.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\pinmap.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\port_api.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\pwmout_api.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\rtc_api.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\serial_api.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\sleep.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\spi_api.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\us_ticker.o   \
				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\TARGET_MTS_MDOT_F405RG\PeripheralPins.o	\
				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\TARGET_MTS_MDOT_F405RG\TOOLCHAIN_GCC_ARM\startup_STM32F40x.o


# 				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4XX\TOOLCHAIN_ARM_STD\sys.o   
#				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4XX\cmsis_nvic.o   \
#				.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4XX\system_stm32f4xx.o   \
# 				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4XX\analogin_api.o   \
# 				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4XX\gpio_api.o   \
# 				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4XX\i2c_api.o   \
# 				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4XX\pinmap.o   \
# 				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4XX\port_api.o   \
# 				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4XX\spi_api.o   \
# 				.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4XX\us_ticker.o   \

SYS_OBJECTS_RTOS = 	\
					.\libraries\rtos\rtos\Mutex.o   \
					.\libraries\rtos\rtos\RtosTimer.o   \
					.\libraries\rtos\rtos\Semaphore.o   \
					.\libraries\rtos\rtos\Thread.o   

SYS_OBJECTS_RTX = 	\
				.\libraries\rtos\rtx\TARGET_CORTEX_M\HAL_CM.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\RTX_Conf_CM.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_CMSIS.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_Event.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_List.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_Mailbox.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_MemBox.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_Mutex.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_Robin.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_Semaphore.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_System.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_Task.o   \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\rt_Time.o  \
				.\libraries\rtos\rtx\TARGET_CORTEX_M\TARGET_M4\TOOLCHAIN_GCC\SVC_Table.o	\
				.\libraries\rtos\rtx\TARGET_CORTEX_M\TARGET_M4\TOOLCHAIN_GCC\HAL_CM4.o

INCLUDE_PATHS = -I. \
				-I.\libraries\mbed\api	\
				-I.\libraries\mbed\hal	\
				-I.\libraries\rtos\rtos	\
				-I.\libraries\rtos\rtx\TARGET_CORTEX_M	\
				-I.\libraries\mbed\targets\cmsis	\
				-I.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4	\
				-I.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\TARGET_MTS_MDOT_F405RG	\
				-I.\libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4XX	\
				-I.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4	\
				-I.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4\TARGET_MTS_MDOT_F405RG	\
				-I.\libraries\mbed\targets\hal\TARGET_STM\TARGET_STM32F4XX



	
LIBRARY_PATHS = -L./libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4/TOOLCHAIN_GCC_ARM 
LIBRARIES =
LINKER_SCRIPT = ./libraries\mbed\targets\cmsis\TARGET_STM\TARGET_STM32F4\TARGET_MTS_MDOT_F405RG\TOOLCHAIN_GCC_ARM/STM32F405.ld


############################################################################### 
AS      = $(GCC_BIN)arm-none-eabi-as
CC      = $(GCC_BIN)arm-none-eabi-gcc
CPP     = $(GCC_BIN)arm-none-eabi-g++
LD      = $(GCC_BIN)arm-none-eabi-gcc
OBJCOPY = $(GCC_BIN)arm-none-eabi-objcopy
OBJDUMP = $(GCC_BIN)arm-none-eabi-objdump
SIZE 	= $(GCC_BIN)arm-none-eabi-size

CPU = -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=$(FLOAT_ABI)
CC_FLAGS = $(CPU) -c -g -fno-common -fmessage-length=0 -Wall -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer
CC_FLAGS += -MMD -MP
CC_SYMBOLS = -DTARGET_STM32F405RG -DTARGET_M4 -DTARGET_CORTEX_M -DTARGET_STM -DTARGET_STM32F4 -DTOOLCHAIN_GCC_ARM -DTOOLCHAIN_GCC -D__CORTEX_M4 -DARM_MATH_CM4 -D__FPU_PRESENT=1 -DMBED_BUILD_TIMESTAMP=1422906069.58 -D__MBED__=1 -DTARGET_FF_ARDUINO -DTARGET_FF_MORPHO 

LD_FLAGS = $(CPU) -Wl,--gc-sections --specs=nano.specs -u _printf_float -u _scanf_float -Wl,--wrap,main
LD_FLAGS += -Wl,-Map=$(PROJECT).map,--cref
LD_SYS_LIBS = -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys

ifeq ($(HARDFP),1)
	FLOAT_ABI = hard
else
	FLOAT_ABI = softfp
endif

ifeq ($(DEBUG), 1)
  CC_FLAGS += -DDEBUG -O0
else
  CC_FLAGS += -DNDEBUG -Os
endif

all: $(PROJECT).srec $(PROJECT).bin $(PROJECT).hex 

clean:
	rm -f $(PROJECT).bin $(PROJECT).elf $(PROJECT).hex $(PROJECT).map $(PROJECT).lst $(OBJECTS) $(DEPS)

.s.o:
	$(AS) $(CPU) -o $@ $<

.c.o:
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu99   $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	$(CPP) $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu++98 -fno-rtti $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).elf: $(SYS_OBJECTS_MBED_TARGETS) $(SYS_OBJECTS_MBED_COMMON) $(SYS_OBJECTS_RTOS) $(SYS_OBJECTS_RTX) $(OBJECTS)
	$(LD) $(LD_FLAGS) -T$(LINKER_SCRIPT) $(LIBRARY_PATHS) -o $@ $^ $(LIBRARIES) $(LD_SYS_LIBS) $(LIBRARIES) $(LD_SYS_LIBS)
	$(SIZE) $@

$(PROJECT).srec: $(PROJECT).elf
	@$(OBJCOPY) $< $@

$(PROJECT).bin: $(PROJECT).elf
	@$(OBJCOPY) -O binary $< $@

$(PROJECT).hex: $(PROJECT).elf
	@$(OBJCOPY) -O ihex $< $@

$(PROJECT).lst: $(PROJECT).elf
	@$(OBJDUMP) -Sdh $< > $@

lst: $(PROJECT).lst

size:
	$(SIZE) $(PROJECT).elf

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
